export const styles = {
  safeAreaView: {
    flex: 1,
    backgroundColor: 'white',
    alignItems: 'center',
    justifyContent: 'space-evenly',
  },
  mainViewStyle: {
    width: '60%',
    height: '10%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  countryText: {
    textAlign: 'center',
    fontSize: 20,
    color: 'blue',
  },
  cityText: {
    textAlign: 'center',
    fontSize: 25,
    color: 'blue',
  },
  weatherDescriptionText: {
    textAlign: 'center',
    fontSize: 20,
    color: 'blue',
    textTransform: 'capitalize',
  },
  middleViewStyle: {
    width: '80%',
    height: '50%',
    borderColor: 'teal',
    borderWidth: 1,
    borderRadius: 30,
    justifyContent: 'space-evenly',
  },
  middleViewText: {
    padding: 10,
    color: 'teal',
    fontSize: 20,
  },
  bottomViewStyle: {
    width: '60%',
    height: '30%',
    justifyContent: 'space-evenly',
  },
  searchButtonStyle: {
    width: 100,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    borderWidth: 1,
    borderColor: 'teal',
    marginTop: 5,
  },
  searchText: {
    fontSize: 15,
    textAlign: 'center',
    color: 'teal',
  },
  deleteButtonStyle: {
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    borderWidth: 1,
    borderColor: 'teal',
    marginTop: 5,
  },
  deleteText: {
    textAlign: 'center',
    fontSize: 15,
    color: 'teal',
    paddingHorizontal: 5,
  },
  favoriteButtonStyle: {
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    borderWidth: 1,
    borderColor: 'teal',
    marginTop: 5,
  },
  favoriteText: {
    textAlign: 'center',
    fontSize: 15,
    color: 'teal',
    paddingHorizontal: 5,
  },
};
